/*
 * Journey Orchestration API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.30.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.alterian.jo.api;

import com.alterian.jo.ApiException;
import java.io.File;
import com.alterian.jo.model.ModelApiResponse;
import com.alterian.jo.model.TargetEnum;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for FileApi
 */
@Disabled
public class FileApiTest {

    private final FileApi api = new FileApi();

    /**
     * Lists files
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void fileClientGetTest() throws ApiException {
        String client = null;
        String searchText = null;
        ModelApiResponse response = api.fileClientGet(client, searchText);
        // TODO: test validations
    }

    /**
     * Remove a file from the server
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void fileClientTargetFilenameDeleteTest() throws ApiException {
        TargetEnum target = null;
        String client = null;
        String filename = null;
        api.fileClientTargetFilenameDelete(target, client, filename);
        // TODO: test validations
    }

    /**
     * Download a file from the server
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void fileClientTargetFilenameGetTest() throws ApiException {
        TargetEnum target = null;
        String client = null;
        String filename = null;
        String searchText = null;
        api.fileClientTargetFilenameGet(target, client, filename, searchText);
        // TODO: test validations
    }

    /**
     * Upload a file to the server
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void fileClientTargetFilenamePostTest() throws ApiException {
        TargetEnum target = null;
        String client = null;
        String filename = null;
        File _file = null;
        api.fileClientTargetFilenamePost(target, client, filename, _file);
        // TODO: test validations
    }

    /**
     * Lists files
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void fileClientTargetGetTest() throws ApiException {
        TargetEnum target = null;
        String client = null;
        String searchText = null;
        ModelApiResponse response = api.fileClientTargetGet(target, client, searchText);
        // TODO: test validations
    }

}
