/*
 * Journey Orchestration API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.30.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.alterian.jo.api;

import com.alterian.jo.ApiException;
import java.io.File;
import com.alterian.jo.model.TargetEnum;
import com.alterian.jo.model.TestDataListingResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TestdataApi
 */
@Disabled
public class TestdataApiTest {

    private final TestdataApi api = new TestdataApi();

    /**
     * Download user defined test data for a specific rule as JSON
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void downloadTestdataTargetClientRulenameGetTest() throws ApiException {
        TargetEnum target = null;
        String client = null;
        String rulename = null;
        File response = api.downloadTestdataTargetClientRulenameGet(target, client, rulename);
        // TODO: test validations
    }

    /**
     * List all user defined test data across all rules.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void testdataGetTest() throws ApiException {
        Integer from = null;
        Integer to = null;
        TestDataListingResponse response = api.testdataGet(from, to);
        // TODO: test validations
    }

}
