/*
 * Journey Orchestration API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.30.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.alterian.jo.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.alterian.jo.JSON;

/**
 * CaseTargetDetails
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.4.0")
public class CaseTargetDetails {
  public static final String SERIALIZED_NAME_CASE_VALUE = "caseValue";
  @SerializedName(SERIALIZED_NAME_CASE_VALUE)
  private String caseValue;

  public static final String SERIALIZED_NAME_CASE_TARGET_STEP_NAME = "caseTargetStepName";
  @SerializedName(SERIALIZED_NAME_CASE_TARGET_STEP_NAME)
  private String caseTargetStepName;

  public CaseTargetDetails() {
  }

  public CaseTargetDetails caseValue(String caseValue) {
    this.caseValue = caseValue;
    return this;
  }

   /**
   * Get caseValue
   * @return caseValue
  **/
  @javax.annotation.Nullable
  public String getCaseValue() {
    return caseValue;
  }

  public void setCaseValue(String caseValue) {
    this.caseValue = caseValue;
  }


  public CaseTargetDetails caseTargetStepName(String caseTargetStepName) {
    this.caseTargetStepName = caseTargetStepName;
    return this;
  }

   /**
   * Get caseTargetStepName
   * @return caseTargetStepName
  **/
  @javax.annotation.Nullable
  public String getCaseTargetStepName() {
    return caseTargetStepName;
  }

  public void setCaseTargetStepName(String caseTargetStepName) {
    this.caseTargetStepName = caseTargetStepName;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CaseTargetDetails caseTargetDetails = (CaseTargetDetails) o;
    return Objects.equals(this.caseValue, caseTargetDetails.caseValue) &&
        Objects.equals(this.caseTargetStepName, caseTargetDetails.caseTargetStepName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(caseValue, caseTargetStepName);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CaseTargetDetails {\n");
    sb.append("    caseValue: ").append(toIndentedString(caseValue)).append("\n");
    sb.append("    caseTargetStepName: ").append(toIndentedString(caseTargetStepName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("caseValue");
    openapiFields.add("caseTargetStepName");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to CaseTargetDetails
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!CaseTargetDetails.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in CaseTargetDetails is not found in the empty JSON string", CaseTargetDetails.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!CaseTargetDetails.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `CaseTargetDetails` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("caseValue") != null && !jsonObj.get("caseValue").isJsonNull()) && !jsonObj.get("caseValue").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `caseValue` to be a primitive type in the JSON string but got `%s`", jsonObj.get("caseValue").toString()));
      }
      if ((jsonObj.get("caseTargetStepName") != null && !jsonObj.get("caseTargetStepName").isJsonNull()) && !jsonObj.get("caseTargetStepName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `caseTargetStepName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("caseTargetStepName").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CaseTargetDetails.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CaseTargetDetails' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CaseTargetDetails> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CaseTargetDetails.class));

       return (TypeAdapter<T>) new TypeAdapter<CaseTargetDetails>() {
           @Override
           public void write(JsonWriter out, CaseTargetDetails value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public CaseTargetDetails read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of CaseTargetDetails given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of CaseTargetDetails
  * @throws IOException if the JSON string is invalid with respect to CaseTargetDetails
  */
  public static CaseTargetDetails fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CaseTargetDetails.class);
  }

 /**
  * Convert an instance of CaseTargetDetails to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

