/*
 * Journey Orchestration API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.29.139
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.alterian.jo.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Time frame for calculating the health score
 */
@JsonAdapter(HealthScoreTimeFrame.Adapter.class)
public enum HealthScoreTimeFrame {
  
  HOUR("hour"),
  
  DAY("day"),
  
  MIN("min"),
  
  UNKNOWN_DEFAULT_OPEN_API("unknown_default_open_api");

  private String value;

  HealthScoreTimeFrame(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static HealthScoreTimeFrame fromValue(String value) {
    for (HealthScoreTimeFrame b : HealthScoreTimeFrame.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    return UNKNOWN_DEFAULT_OPEN_API;
  }

  public static class Adapter extends TypeAdapter<HealthScoreTimeFrame> {
    @Override
    public void write(final JsonWriter jsonWriter, final HealthScoreTimeFrame enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public HealthScoreTimeFrame read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return HealthScoreTimeFrame.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    HealthScoreTimeFrame.fromValue(value);
  }
}

