/*
 * Journey Orchestration API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.29.139
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.alterian.jo.model;

import java.util.Objects;
import com.alterian.jo.model.OutputConnectorRealtimeOutputStepsInner;
import com.alterian.jo.model.OutputField;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.alterian.jo.JSON;

/**
 * OutputConnector
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.4.0")
public class OutputConnector {
  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_ACTIVE = "active";
  @SerializedName(SERIALIZED_NAME_ACTIVE)
  private Boolean active;

  public static final String SERIALIZED_NAME_DISABLED = "disabled";
  @SerializedName(SERIALIZED_NAME_DISABLED)
  private Boolean disabled;

  public static final String SERIALIZED_NAME_FIELDS = "fields";
  @SerializedName(SERIALIZED_NAME_FIELDS)
  private List<OutputField> fields;

  public static final String SERIALIZED_NAME_REALTIME_OUTPUT_STEPS = "realtimeOutputSteps";
  @SerializedName(SERIALIZED_NAME_REALTIME_OUTPUT_STEPS)
  private List<OutputConnectorRealtimeOutputStepsInner> realtimeOutputSteps;

  public static final String SERIALIZED_NAME_CONNECTED_INPUTS = "connectedInputs";
  @SerializedName(SERIALIZED_NAME_CONNECTED_INPUTS)
  private List<String> connectedInputs;

  public OutputConnector() {
  }

  public OutputConnector name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nullable
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }


  public OutputConnector active(Boolean active) {
    this.active = active;
    return this;
  }

   /**
   * Get active
   * @return active
  **/
  @javax.annotation.Nullable
  public Boolean getActive() {
    return active;
  }

  public void setActive(Boolean active) {
    this.active = active;
  }


  public OutputConnector disabled(Boolean disabled) {
    this.disabled = disabled;
    return this;
  }

   /**
   * Get disabled
   * @return disabled
  **/
  @javax.annotation.Nullable
  public Boolean getDisabled() {
    return disabled;
  }

  public void setDisabled(Boolean disabled) {
    this.disabled = disabled;
  }


  public OutputConnector fields(List<OutputField> fields) {
    this.fields = fields;
    return this;
  }

  public OutputConnector addFieldsItem(OutputField fieldsItem) {
    if (this.fields == null) {
      this.fields = new ArrayList<>();
    }
    this.fields.add(fieldsItem);
    return this;
  }

   /**
   * Get fields
   * @return fields
  **/
  @javax.annotation.Nullable
  public List<OutputField> getFields() {
    return fields;
  }

  public void setFields(List<OutputField> fields) {
    this.fields = fields;
  }


  public OutputConnector realtimeOutputSteps(List<OutputConnectorRealtimeOutputStepsInner> realtimeOutputSteps) {
    this.realtimeOutputSteps = realtimeOutputSteps;
    return this;
  }

  public OutputConnector addRealtimeOutputStepsItem(OutputConnectorRealtimeOutputStepsInner realtimeOutputStepsItem) {
    if (this.realtimeOutputSteps == null) {
      this.realtimeOutputSteps = new ArrayList<>();
    }
    this.realtimeOutputSteps.add(realtimeOutputStepsItem);
    return this;
  }

   /**
   * Get realtimeOutputSteps
   * @return realtimeOutputSteps
  **/
  @javax.annotation.Nullable
  public List<OutputConnectorRealtimeOutputStepsInner> getRealtimeOutputSteps() {
    return realtimeOutputSteps;
  }

  public void setRealtimeOutputSteps(List<OutputConnectorRealtimeOutputStepsInner> realtimeOutputSteps) {
    this.realtimeOutputSteps = realtimeOutputSteps;
  }


  public OutputConnector connectedInputs(List<String> connectedInputs) {
    this.connectedInputs = connectedInputs;
    return this;
  }

  public OutputConnector addConnectedInputsItem(String connectedInputsItem) {
    if (this.connectedInputs == null) {
      this.connectedInputs = new ArrayList<>();
    }
    this.connectedInputs.add(connectedInputsItem);
    return this;
  }

   /**
   * Get connectedInputs
   * @return connectedInputs
  **/
  @javax.annotation.Nullable
  public List<String> getConnectedInputs() {
    return connectedInputs;
  }

  public void setConnectedInputs(List<String> connectedInputs) {
    this.connectedInputs = connectedInputs;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OutputConnector outputConnector = (OutputConnector) o;
    return Objects.equals(this.name, outputConnector.name) &&
        Objects.equals(this.active, outputConnector.active) &&
        Objects.equals(this.disabled, outputConnector.disabled) &&
        Objects.equals(this.fields, outputConnector.fields) &&
        Objects.equals(this.realtimeOutputSteps, outputConnector.realtimeOutputSteps) &&
        Objects.equals(this.connectedInputs, outputConnector.connectedInputs);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, active, disabled, fields, realtimeOutputSteps, connectedInputs);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OutputConnector {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    active: ").append(toIndentedString(active)).append("\n");
    sb.append("    disabled: ").append(toIndentedString(disabled)).append("\n");
    sb.append("    fields: ").append(toIndentedString(fields)).append("\n");
    sb.append("    realtimeOutputSteps: ").append(toIndentedString(realtimeOutputSteps)).append("\n");
    sb.append("    connectedInputs: ").append(toIndentedString(connectedInputs)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("name");
    openapiFields.add("active");
    openapiFields.add("disabled");
    openapiFields.add("fields");
    openapiFields.add("realtimeOutputSteps");
    openapiFields.add("connectedInputs");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to OutputConnector
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!OutputConnector.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in OutputConnector is not found in the empty JSON string", OutputConnector.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!OutputConnector.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `OutputConnector` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("name") != null && !jsonObj.get("name").isJsonNull()) && !jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if (jsonObj.get("fields") != null && !jsonObj.get("fields").isJsonNull()) {
        JsonArray jsonArrayfields = jsonObj.getAsJsonArray("fields");
        if (jsonArrayfields != null) {
          // ensure the json data is an array
          if (!jsonObj.get("fields").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `fields` to be an array in the JSON string but got `%s`", jsonObj.get("fields").toString()));
          }

          // validate the optional field `fields` (array)
          for (int i = 0; i < jsonArrayfields.size(); i++) {
            OutputField.validateJsonElement(jsonArrayfields.get(i));
          };
        }
      }
      if (jsonObj.get("realtimeOutputSteps") != null && !jsonObj.get("realtimeOutputSteps").isJsonNull()) {
        JsonArray jsonArrayrealtimeOutputSteps = jsonObj.getAsJsonArray("realtimeOutputSteps");
        if (jsonArrayrealtimeOutputSteps != null) {
          // ensure the json data is an array
          if (!jsonObj.get("realtimeOutputSteps").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `realtimeOutputSteps` to be an array in the JSON string but got `%s`", jsonObj.get("realtimeOutputSteps").toString()));
          }

          // validate the optional field `realtimeOutputSteps` (array)
          for (int i = 0; i < jsonArrayrealtimeOutputSteps.size(); i++) {
            OutputConnectorRealtimeOutputStepsInner.validateJsonElement(jsonArrayrealtimeOutputSteps.get(i));
          };
        }
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("connectedInputs") != null && !jsonObj.get("connectedInputs").isJsonNull() && !jsonObj.get("connectedInputs").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `connectedInputs` to be an array in the JSON string but got `%s`", jsonObj.get("connectedInputs").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!OutputConnector.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'OutputConnector' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<OutputConnector> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(OutputConnector.class));

       return (TypeAdapter<T>) new TypeAdapter<OutputConnector>() {
           @Override
           public void write(JsonWriter out, OutputConnector value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public OutputConnector read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of OutputConnector given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of OutputConnector
  * @throws IOException if the JSON string is invalid with respect to OutputConnector
  */
  public static OutputConnector fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, OutputConnector.class);
  }

 /**
  * Convert an instance of OutputConnector to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

