/*
 * Journey Orchestration API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.30.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.alterian.jo.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.alterian.jo.JSON;

/**
 * TemplateColumnReport
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.4.0")
public class TemplateColumnReport {
  public static final String SERIALIZED_NAME_TABLE = "table";
  @SerializedName(SERIALIZED_NAME_TABLE)
  private String table;

  public static final String SERIALIZED_NAME_COLUMN = "column";
  @SerializedName(SERIALIZED_NAME_COLUMN)
  private String column;

  public static final String SERIALIZED_NAME_MATCHEDTEMPLATES = "matchedtemplates";
  @SerializedName(SERIALIZED_NAME_MATCHEDTEMPLATES)
  private List<String> matchedtemplates;

  public TemplateColumnReport() {
  }

  public TemplateColumnReport table(String table) {
    this.table = table;
    return this;
  }

   /**
   * Get table
   * @return table
  **/
  @javax.annotation.Nullable
  public String getTable() {
    return table;
  }

  public void setTable(String table) {
    this.table = table;
  }


  public TemplateColumnReport column(String column) {
    this.column = column;
    return this;
  }

   /**
   * Get column
   * @return column
  **/
  @javax.annotation.Nullable
  public String getColumn() {
    return column;
  }

  public void setColumn(String column) {
    this.column = column;
  }


  public TemplateColumnReport matchedtemplates(List<String> matchedtemplates) {
    this.matchedtemplates = matchedtemplates;
    return this;
  }

  public TemplateColumnReport addMatchedtemplatesItem(String matchedtemplatesItem) {
    if (this.matchedtemplates == null) {
      this.matchedtemplates = new ArrayList<>();
    }
    this.matchedtemplates.add(matchedtemplatesItem);
    return this;
  }

   /**
   * Get matchedtemplates
   * @return matchedtemplates
  **/
  @javax.annotation.Nullable
  public List<String> getMatchedtemplates() {
    return matchedtemplates;
  }

  public void setMatchedtemplates(List<String> matchedtemplates) {
    this.matchedtemplates = matchedtemplates;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TemplateColumnReport templateColumnReport = (TemplateColumnReport) o;
    return Objects.equals(this.table, templateColumnReport.table) &&
        Objects.equals(this.column, templateColumnReport.column) &&
        Objects.equals(this.matchedtemplates, templateColumnReport.matchedtemplates);
  }

  @Override
  public int hashCode() {
    return Objects.hash(table, column, matchedtemplates);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TemplateColumnReport {\n");
    sb.append("    table: ").append(toIndentedString(table)).append("\n");
    sb.append("    column: ").append(toIndentedString(column)).append("\n");
    sb.append("    matchedtemplates: ").append(toIndentedString(matchedtemplates)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("table");
    openapiFields.add("column");
    openapiFields.add("matchedtemplates");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to TemplateColumnReport
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!TemplateColumnReport.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in TemplateColumnReport is not found in the empty JSON string", TemplateColumnReport.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!TemplateColumnReport.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `TemplateColumnReport` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("table") != null && !jsonObj.get("table").isJsonNull()) && !jsonObj.get("table").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `table` to be a primitive type in the JSON string but got `%s`", jsonObj.get("table").toString()));
      }
      if ((jsonObj.get("column") != null && !jsonObj.get("column").isJsonNull()) && !jsonObj.get("column").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `column` to be a primitive type in the JSON string but got `%s`", jsonObj.get("column").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("matchedtemplates") != null && !jsonObj.get("matchedtemplates").isJsonNull() && !jsonObj.get("matchedtemplates").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `matchedtemplates` to be an array in the JSON string but got `%s`", jsonObj.get("matchedtemplates").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!TemplateColumnReport.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'TemplateColumnReport' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<TemplateColumnReport> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(TemplateColumnReport.class));

       return (TypeAdapter<T>) new TypeAdapter<TemplateColumnReport>() {
           @Override
           public void write(JsonWriter out, TemplateColumnReport value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public TemplateColumnReport read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of TemplateColumnReport given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of TemplateColumnReport
  * @throws IOException if the JSON string is invalid with respect to TemplateColumnReport
  */
  public static TemplateColumnReport fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, TemplateColumnReport.class);
  }

 /**
  * Convert an instance of TemplateColumnReport to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

