/*
 * Journey Orchestration API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.30.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.alterian.jo.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.alterian.jo.JSON;

/**
 * TemplateInputReport
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.4.0")
public class TemplateInputReport {
  public static final String SERIALIZED_NAME_TEMPLATE_URL = "templateUrl";
  @SerializedName(SERIALIZED_NAME_TEMPLATE_URL)
  private String templateUrl;

  public static final String SERIALIZED_NAME_INPUT_FIELDS = "inputFields";
  @SerializedName(SERIALIZED_NAME_INPUT_FIELDS)
  private List<String> inputFields;

  public TemplateInputReport() {
  }

  public TemplateInputReport templateUrl(String templateUrl) {
    this.templateUrl = templateUrl;
    return this;
  }

   /**
   * Get templateUrl
   * @return templateUrl
  **/
  @javax.annotation.Nullable
  public String getTemplateUrl() {
    return templateUrl;
  }

  public void setTemplateUrl(String templateUrl) {
    this.templateUrl = templateUrl;
  }


  public TemplateInputReport inputFields(List<String> inputFields) {
    this.inputFields = inputFields;
    return this;
  }

  public TemplateInputReport addInputFieldsItem(String inputFieldsItem) {
    if (this.inputFields == null) {
      this.inputFields = new ArrayList<>();
    }
    this.inputFields.add(inputFieldsItem);
    return this;
  }

   /**
   * Get inputFields
   * @return inputFields
  **/
  @javax.annotation.Nullable
  public List<String> getInputFields() {
    return inputFields;
  }

  public void setInputFields(List<String> inputFields) {
    this.inputFields = inputFields;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TemplateInputReport templateInputReport = (TemplateInputReport) o;
    return Objects.equals(this.templateUrl, templateInputReport.templateUrl) &&
        Objects.equals(this.inputFields, templateInputReport.inputFields);
  }

  @Override
  public int hashCode() {
    return Objects.hash(templateUrl, inputFields);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TemplateInputReport {\n");
    sb.append("    templateUrl: ").append(toIndentedString(templateUrl)).append("\n");
    sb.append("    inputFields: ").append(toIndentedString(inputFields)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("templateUrl");
    openapiFields.add("inputFields");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to TemplateInputReport
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!TemplateInputReport.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in TemplateInputReport is not found in the empty JSON string", TemplateInputReport.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!TemplateInputReport.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `TemplateInputReport` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("templateUrl") != null && !jsonObj.get("templateUrl").isJsonNull()) && !jsonObj.get("templateUrl").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `templateUrl` to be a primitive type in the JSON string but got `%s`", jsonObj.get("templateUrl").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("inputFields") != null && !jsonObj.get("inputFields").isJsonNull() && !jsonObj.get("inputFields").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `inputFields` to be an array in the JSON string but got `%s`", jsonObj.get("inputFields").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!TemplateInputReport.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'TemplateInputReport' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<TemplateInputReport> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(TemplateInputReport.class));

       return (TypeAdapter<T>) new TypeAdapter<TemplateInputReport>() {
           @Override
           public void write(JsonWriter out, TemplateInputReport value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public TemplateInputReport read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of TemplateInputReport given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of TemplateInputReport
  * @throws IOException if the JSON string is invalid with respect to TemplateInputReport
  */
  public static TemplateInputReport fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, TemplateInputReport.class);
  }

 /**
  * Convert an instance of TemplateInputReport to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

