/*
 * Journey Orchestration API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.30.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.alterian.jo.model;

import java.util.Objects;
import com.alterian.jo.model.TestData;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.alterian.jo.JSON;

/**
 * TestDataItem
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.4.0")
public class TestDataItem {
  public static final String SERIALIZED_NAME_TEST_DATA = "testData";
  @SerializedName(SERIALIZED_NAME_TEST_DATA)
  private List<TestData> testData;

  public static final String SERIALIZED_NAME_STEP_TYPE = "stepType";
  @SerializedName(SERIALIZED_NAME_STEP_TYPE)
  private String stepType;

  public TestDataItem() {
  }

  public TestDataItem testData(List<TestData> testData) {
    this.testData = testData;
    return this;
  }

  public TestDataItem addTestDataItem(TestData testDataItem) {
    if (this.testData == null) {
      this.testData = new ArrayList<>();
    }
    this.testData.add(testDataItem);
    return this;
  }

   /**
   * Get testData
   * @return testData
  **/
  @javax.annotation.Nullable
  public List<TestData> getTestData() {
    return testData;
  }

  public void setTestData(List<TestData> testData) {
    this.testData = testData;
  }


  public TestDataItem stepType(String stepType) {
    this.stepType = stepType;
    return this;
  }

   /**
   * Get stepType
   * @return stepType
  **/
  @javax.annotation.Nullable
  public String getStepType() {
    return stepType;
  }

  public void setStepType(String stepType) {
    this.stepType = stepType;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TestDataItem testDataItem = (TestDataItem) o;
    return Objects.equals(this.testData, testDataItem.testData) &&
        Objects.equals(this.stepType, testDataItem.stepType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(testData, stepType);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TestDataItem {\n");
    sb.append("    testData: ").append(toIndentedString(testData)).append("\n");
    sb.append("    stepType: ").append(toIndentedString(stepType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("testData");
    openapiFields.add("stepType");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to TestDataItem
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!TestDataItem.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in TestDataItem is not found in the empty JSON string", TestDataItem.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!TestDataItem.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `TestDataItem` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (jsonObj.get("testData") != null && !jsonObj.get("testData").isJsonNull()) {
        JsonArray jsonArraytestData = jsonObj.getAsJsonArray("testData");
        if (jsonArraytestData != null) {
          // ensure the json data is an array
          if (!jsonObj.get("testData").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `testData` to be an array in the JSON string but got `%s`", jsonObj.get("testData").toString()));
          }

          // validate the optional field `testData` (array)
          for (int i = 0; i < jsonArraytestData.size(); i++) {
            TestData.validateJsonElement(jsonArraytestData.get(i));
          };
        }
      }
      if ((jsonObj.get("stepType") != null && !jsonObj.get("stepType").isJsonNull()) && !jsonObj.get("stepType").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `stepType` to be a primitive type in the JSON string but got `%s`", jsonObj.get("stepType").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!TestDataItem.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'TestDataItem' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<TestDataItem> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(TestDataItem.class));

       return (TypeAdapter<T>) new TypeAdapter<TestDataItem>() {
           @Override
           public void write(JsonWriter out, TestDataItem value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public TestDataItem read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of TestDataItem given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of TestDataItem
  * @throws IOException if the JSON string is invalid with respect to TestDataItem
  */
  public static TestDataItem fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, TestDataItem.class);
  }

 /**
  * Convert an instance of TestDataItem to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

