/*
 * Journey Orchestration API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.30.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.alterian.jo.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CacheApiData
 */
public class CacheApiDataTest {
    private final CacheApiData model = new CacheApiData();

    /**
     * Model tests for CacheApiData
     */
    @Test
    public void testCacheApiData() {
        // TODO: test CacheApiData
    }

    /**
     * Test the property 'wasapplied'
     */
    @Test
    public void wasappliedTest() {
        // TODO: test wasapplied
    }

}
