/*
 * Journey Orchestration API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.29.139
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.alterian.jo.model;

import com.alterian.jo.model.CacheConsistencyLevel;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CacheCQL
 */
public class CacheCQLTest {
    private final CacheCQL model = new CacheCQL();

    /**
     * Model tests for CacheCQL
     */
    @Test
    public void testCacheCQL() {
        // TODO: test CacheCQL
    }

    /**
     * Test the property 'consistency'
     */
    @Test
    public void consistencyTest() {
        // TODO: test consistency
    }

    /**
     * Test the property 'cql'
     */
    @Test
    public void cqlTest() {
        // TODO: test cql
    }

    /**
     * Test the property 'retries'
     */
    @Test
    public void retriesTest() {
        // TODO: test retries
    }

}
