/*
 * Journey Orchestration API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.29.139
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.alterian.jo.model;

import com.alterian.jo.model.CacheExecuteData;
import com.alterian.jo.model.SuccessCursor;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CacheExecuteResponse
 */
public class CacheExecuteResponseTest {
    private final CacheExecuteResponse model = new CacheExecuteResponse();

    /**
     * Model tests for CacheExecuteResponse
     */
    @Test
    public void testCacheExecuteResponse() {
        // TODO: test CacheExecuteResponse
    }

    /**
     * Test the property 'cursor'
     */
    @Test
    public void cursorTest() {
        // TODO: test cursor
    }

    /**
     * Test the property 'debug'
     */
    @Test
    public void debugTest() {
        // TODO: test debug
    }

    /**
     * Test the property 'exceptionType'
     */
    @Test
    public void exceptionTypeTest() {
        // TODO: test exceptionType
    }

    /**
     * Test the property 'message'
     */
    @Test
    public void messageTest() {
        // TODO: test message
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'data'
     */
    @Test
    public void dataTest() {
        // TODO: test data
    }

}
