/*
 * Journey Orchestration API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.29.139
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.alterian.jo.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Client
 */
public class ClientTest {
    private final Client model = new Client();

    /**
     * Model tests for Client
     */
    @Test
    public void testClient() {
        // TODO: test Client
    }

    /**
     * Test the property 'defaultCacheDuration'
     */
    @Test
    public void defaultCacheDurationTest() {
        // TODO: test defaultCacheDuration
    }

}
