/*
 * Journey Orchestration API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.30.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.alterian.jo.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ConversationUsageReport
 */
public class ConversationUsageReportTest {
    private final ConversationUsageReport model = new ConversationUsageReport();

    /**
     * Model tests for ConversationUsageReport
     */
    @Test
    public void testConversationUsageReport() {
        // TODO: test ConversationUsageReport
    }

    /**
     * Test the property 'timestamp'
     */
    @Test
    public void timestampTest() {
        // TODO: test timestamp
    }

    /**
     * Test the property 'conversations'
     */
    @Test
    public void conversationsTest() {
        // TODO: test conversations
    }

    /**
     * Test the property 'activeConversations'
     */
    @Test
    public void activeConversationsTest() {
        // TODO: test activeConversations
    }

    /**
     * Test the property 'bulkLoads'
     */
    @Test
    public void bulkLoadsTest() {
        // TODO: test bulkLoads
    }

}
