/*
 * Journey Orchestration API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.29.139
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.alterian.jo.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Icon
 */
public class IconTest {
    private final Icon model = new Icon();

    /**
     * Model tests for Icon
     */
    @Test
    public void testIcon() {
        // TODO: test Icon
    }

    /**
     * Test the property 'background'
     */
    @Test
    public void backgroundTest() {
        // TODO: test background
    }

    /**
     * Test the property 'svgIcon'
     */
    @Test
    public void svgIconTest() {
        // TODO: test svgIcon
    }

    /**
     * Test the property 'foreground'
     */
    @Test
    public void foregroundTest() {
        // TODO: test foreground
    }

    /**
     * Test the property 'matIcon'
     */
    @Test
    public void matIconTest() {
        // TODO: test matIcon
    }

}
