/*
 * Journey Orchestration API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.30.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.alterian.jo.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Opportunitygrid
 */
public class OpportunitygridTest {
    private final Opportunitygrid model = new Opportunitygrid();

    /**
     * Model tests for Opportunitygrid
     */
    @Test
    public void testOpportunitygrid() {
        // TODO: test Opportunitygrid
    }

    /**
     * Test the property 'opportunity'
     */
    @Test
    public void opportunityTest() {
        // TODO: test opportunity
    }

    /**
     * Test the property 'story'
     */
    @Test
    public void storyTest() {
        // TODO: test story
    }

}
