/*
 * Journey Orchestration API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.30.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.alterian.jo.model;

import com.alterian.jo.model.OutputConnectorRealtimeOutputStepsInner;
import com.alterian.jo.model.OutputField;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for OutputConnector
 */
public class OutputConnectorTest {
    private final OutputConnector model = new OutputConnector();

    /**
     * Model tests for OutputConnector
     */
    @Test
    public void testOutputConnector() {
        // TODO: test OutputConnector
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'active'
     */
    @Test
    public void activeTest() {
        // TODO: test active
    }

    /**
     * Test the property 'disabled'
     */
    @Test
    public void disabledTest() {
        // TODO: test disabled
    }

    /**
     * Test the property 'fields'
     */
    @Test
    public void fieldsTest() {
        // TODO: test fields
    }

    /**
     * Test the property 'realtimeOutputSteps'
     */
    @Test
    public void realtimeOutputStepsTest() {
        // TODO: test realtimeOutputSteps
    }

    /**
     * Test the property 'connectedInputs'
     */
    @Test
    public void connectedInputsTest() {
        // TODO: test connectedInputs
    }

}
