/*
 * Journey Orchestration API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.29.139
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.alterian.jo.model;

import com.alterian.jo.model.PickListItem;
import com.alterian.jo.model.TargetValue;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Parameter
 */
public class ParameterTest {
    private final Parameter model = new Parameter();

    /**
     * Model tests for Parameter
     */
    @Test
    public void testParameter() {
        // TODO: test Parameter
    }

    /**
     * Test the property 'businessGoal'
     */
    @Test
    public void businessGoalTest() {
        // TODO: test businessGoal
    }

    /**
     * Test the property 'client'
     */
    @Test
    public void clientTest() {
        // TODO: test client
    }

    /**
     * Test the property 'dataType'
     */
    @Test
    public void dataTypeTest() {
        // TODO: test dataType
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'globalParam'
     */
    @Test
    public void globalParamTest() {
        // TODO: test globalParam
    }

    /**
     * Test the property 'isConfidential'
     */
    @Test
    public void isConfidentialTest() {
        // TODO: test isConfidential
    }

    /**
     * Test the property 'isEditable'
     */
    @Test
    public void isEditableTest() {
        // TODO: test isEditable
    }

    /**
     * Test the property 'isForcedValue'
     */
    @Test
    public void isForcedValueTest() {
        // TODO: test isForcedValue
    }

    /**
     * Test the property 'isVisible'
     */
    @Test
    public void isVisibleTest() {
        // TODO: test isVisible
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'picklistItems'
     */
    @Test
    public void picklistItemsTest() {
        // TODO: test picklistItems
    }

    /**
     * Test the property 'requiresAdmin'
     */
    @Test
    public void requiresAdminTest() {
        // TODO: test requiresAdmin
    }

    /**
     * Test the property 'targets'
     */
    @Test
    public void targetsTest() {
        // TODO: test targets
    }

    /**
     * Test the property 'units'
     */
    @Test
    public void unitsTest() {
        // TODO: test units
    }

    /**
     * Test the property 'url'
     */
    @Test
    public void urlTest() {
        // TODO: test url
    }

}
