/*
 * Journey Orchestration API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.30.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.alterian.jo.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PercentileStatistics
 */
public class PercentileStatisticsTest {
    private final PercentileStatistics model = new PercentileStatistics();

    /**
     * Model tests for PercentileStatistics
     */
    @Test
    public void testPercentileStatistics() {
        // TODO: test PercentileStatistics
    }

    /**
     * Test the property 'p10'
     */
    @Test
    public void p10Test() {
        // TODO: test p10
    }

    /**
     * Test the property 'p20'
     */
    @Test
    public void p20Test() {
        // TODO: test p20
    }

    /**
     * Test the property 'p30'
     */
    @Test
    public void p30Test() {
        // TODO: test p30
    }

    /**
     * Test the property 'p40'
     */
    @Test
    public void p40Test() {
        // TODO: test p40
    }

    /**
     * Test the property 'p50'
     */
    @Test
    public void p50Test() {
        // TODO: test p50
    }

    /**
     * Test the property 'p60'
     */
    @Test
    public void p60Test() {
        // TODO: test p60
    }

    /**
     * Test the property 'p70'
     */
    @Test
    public void p70Test() {
        // TODO: test p70
    }

    /**
     * Test the property 'p80'
     */
    @Test
    public void p80Test() {
        // TODO: test p80
    }

    /**
     * Test the property 'p90'
     */
    @Test
    public void p90Test() {
        // TODO: test p90
    }

    /**
     * Test the property 'p99'
     */
    @Test
    public void p99Test() {
        // TODO: test p99
    }

    /**
     * Test the property 'count'
     */
    @Test
    public void countTest() {
        // TODO: test count
    }

    /**
     * Test the property 'max'
     */
    @Test
    public void maxTest() {
        // TODO: test max
    }

    /**
     * Test the property 'min'
     */
    @Test
    public void minTest() {
        // TODO: test min
    }

}
