/*
 * Journey Orchestration API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.30.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.alterian.jo.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for RuleCallDetails
 */
public class RuleCallDetailsTest {
    private final RuleCallDetails model = new RuleCallDetails();

    /**
     * Model tests for RuleCallDetails
     */
    @Test
    public void testRuleCallDetails() {
        // TODO: test RuleCallDetails
    }

    /**
     * Test the property 'stepName'
     */
    @Test
    public void stepNameTest() {
        // TODO: test stepName
    }

    /**
     * Test the property 'client'
     */
    @Test
    public void clientTest() {
        // TODO: test client
    }

    /**
     * Test the property 'ruleName'
     */
    @Test
    public void ruleNameTest() {
        // TODO: test ruleName
    }

    /**
     * Test the property 'ruleUrl'
     */
    @Test
    public void ruleUrlTest() {
        // TODO: test ruleUrl
    }

    /**
     * Test the property 'target'
     */
    @Test
    public void targetTest() {
        // TODO: test target
    }

}
