/*
 * Journey Orchestration API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.30.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.alterian.jo.model;

import com.alterian.jo.model.Icon;
import com.alterian.jo.model.PickListItem;
import com.alterian.jo.model.RuleGroupParameterDefaultValue;
import com.alterian.jo.model.TargetValue;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for RuleGroupParameter
 */
public class RuleGroupParameterTest {
    private final RuleGroupParameter model = new RuleGroupParameter();

    /**
     * Model tests for RuleGroupParameter
     */
    @Test
    public void testRuleGroupParameter() {
        // TODO: test RuleGroupParameter
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'usingGlobal'
     */
    @Test
    public void usingGlobalTest() {
        // TODO: test usingGlobal
    }

    /**
     * Test the property 'isEditable'
     */
    @Test
    public void isEditableTest() {
        // TODO: test isEditable
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'position'
     */
    @Test
    public void positionTest() {
        // TODO: test position
    }

    /**
     * Test the property 'referencedProperty'
     */
    @Test
    public void referencedPropertyTest() {
        // TODO: test referencedProperty
    }

    /**
     * Test the property 'referencedRule'
     */
    @Test
    public void referencedRuleTest() {
        // TODO: test referencedRule
    }

    /**
     * Test the property 'propertyType'
     */
    @Test
    public void propertyTypeTest() {
        // TODO: test propertyType
    }

    /**
     * Test the property 'units'
     */
    @Test
    public void unitsTest() {
        // TODO: test units
    }

    /**
     * Test the property 'globalParam'
     */
    @Test
    public void globalParamTest() {
        // TODO: test globalParam
    }

    /**
     * Test the property 'defaultValue'
     */
    @Test
    public void defaultValueTest() {
        // TODO: test defaultValue
    }

    /**
     * Test the property 'isVisible'
     */
    @Test
    public void isVisibleTest() {
        // TODO: test isVisible
    }

    /**
     * Test the property 'templatename'
     */
    @Test
    public void templatenameTest() {
        // TODO: test templatename
    }

    /**
     * Test the property 'dataType'
     */
    @Test
    public void dataTypeTest() {
        // TODO: test dataType
    }

    /**
     * Test the property 'targets'
     */
    @Test
    public void targetsTest() {
        // TODO: test targets
    }

    /**
     * Test the property 'pickListItems'
     */
    @Test
    public void pickListItemsTest() {
        // TODO: test pickListItems
    }

    /**
     * Test the property 'iconAndColor'
     */
    @Test
    public void iconAndColorTest() {
        // TODO: test iconAndColor
    }

    /**
     * Test the property 'templateId'
     */
    @Test
    public void templateIdTest() {
        // TODO: test templateId
    }

}
