/*
 * Journey Orchestration API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.29.139
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.alterian.jo.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for RulegroupPostRequest
 */
public class RulegroupPostRequestTest {
    private final RulegroupPostRequest model = new RulegroupPostRequest();

    /**
     * Model tests for RulegroupPostRequest
     */
    @Test
    public void testRulegroupPostRequest() {
        // TODO: test RulegroupPostRequest
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'enableInvoke'
     */
    @Test
    public void enableInvokeTest() {
        // TODO: test enableInvoke
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'referencedRules'
     */
    @Test
    public void referencedRulesTest() {
        // TODO: test referencedRules
    }

}
