/*
 * Journey Orchestration API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.29.139
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.alterian.jo.model;

import com.alterian.jo.model.CaseTargetDetails;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SwitchCaseDetails
 */
public class SwitchCaseDetailsTest {
    private final SwitchCaseDetails model = new SwitchCaseDetails();

    /**
     * Model tests for SwitchCaseDetails
     */
    @Test
    public void testSwitchCaseDetails() {
        // TODO: test SwitchCaseDetails
    }

    /**
     * Test the property 'caseTargets'
     */
    @Test
    public void caseTargetsTest() {
        // TODO: test caseTargets
    }

    /**
     * Test the property 'stepName'
     */
    @Test
    public void stepNameTest() {
        // TODO: test stepName
    }

    /**
     * Test the property 'active'
     */
    @Test
    public void activeTest() {
        // TODO: test active
    }

    /**
     * Test the property 'defaultCaseTarget'
     */
    @Test
    public void defaultCaseTargetTest() {
        // TODO: test defaultCaseTarget
    }

    /**
     * Test the property 'isContains'
     */
    @Test
    public void isContainsTest() {
        // TODO: test isContains
    }

}
