/*
 * Journey Orchestration API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.30.49
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.alterian.jo.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for TemplateColumnReport
 */
public class TemplateColumnReportTest {
    private final TemplateColumnReport model = new TemplateColumnReport();

    /**
     * Model tests for TemplateColumnReport
     */
    @Test
    public void testTemplateColumnReport() {
        // TODO: test TemplateColumnReport
    }

    /**
     * Test the property 'table'
     */
    @Test
    public void tableTest() {
        // TODO: test table
    }

    /**
     * Test the property 'column'
     */
    @Test
    public void columnTest() {
        // TODO: test column
    }

    /**
     * Test the property 'matchedtemplates'
     */
    @Test
    public void matchedtemplatesTest() {
        // TODO: test matchedtemplates
    }

}
